@startdot
graph ER {
    fontname="Helvetica,Arial,sans-serif"
    node [fontname="Helvetica,Arial,sans-serif"]
    edge [fontname="Helvetica,Arial,sans-serif"]
    ' layout=fdp
    ' layout=neato
    ' layout=circo
    layout=twopi
    ' layout=sfdp
    node [shape=box]; Samples; Room; Status;
    node [shape=ellipse]; Temperature; Hall; Owner; Floor; Discription;
    Timestamp [label=<<U>Timestamp</U>> shape=ellipse];
    RoomID [label=<<U>RoomID</U>> shape=diamond];
    StatusID [label=<<U>StatusID</U>> shape=diamond];

    Samples -- RoomID [label="1"];
    RoomID -- Room [label="N"];
    Samples -- StatusID [label="1"];
    StatusID -- Status [label="N"];
    Samples -- Timestamp;
    Samples -- Temperature;
    Samples -- Hall
    Room -- Owner;
    Room -- Floor;
    Room -- Name;
    Status -- Discription;

    label = "\n\nEntity Relation Diagram S6-DTB";
    fontsize=15;
}
@enddot