@startuml

' configuration
hide circle
skinparam linetype ortho
left to right direction

' gradient
!define TABLE_GRADIENT_BACKGROUND #F2F2F2-fcffd6

skinparam class {
    BackgroundColor TABLE_GRADIENT_BACKGROUND
    BorderColor Black
    ArrowColor Blue
 FontSize 13
}

entity "rooms" as rooms {
  id: INT <<PK>>
  --
  name: TEXT
  floor: INT
  owner: TEXT
}

entity "samples" as samples {
  timestamp: TEXT <<PK>>
  --
  status: INT <<FK>>
  temperature: REAL
  room_id: INT <<FK>>
  hall: REAL
}

entity "status" as status {
  id: INT <<PK>>
  --
  description: TEXT
}

samples }.. rooms
samples }.. status

@enduml